apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\dmrka\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: telemedicine-service
  name: telemedicine-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: telemedicine-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\dmrka\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: telemedicine-service
    spec:
      containers:
        - env:
            - name: AGORA_APP_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: healthcare-secrets
                  key: AGORA_APP_CERTIFICATE
            - name: AGORA_APP_ID
              valueFrom:
                secretKeyRef:
                  name: healthcare-secrets
                  key: AGORA_APP_ID
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: healthcare-secrets
                  key: INTERNAL_API_KEY
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: healthcare-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/telemedicine_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
          image: telemedicine-service:latest
          name: telemedicine-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8087
              protocol: TCP
      restartPolicy: Always
